export const precisionOptions = [
  { label: "1.0", value: "1.0" },
  { label: "1.00", value: "1.00" },
  { label: "1.000", value: "1.000" },
  { label: "1.0000", value: "1.0000" },
  { label: "1.00000", value: "1.00000" },
  { label: "1.000000", value: "1.000000" },
];

// defined currency options
export const currencyOptions = [
  { label: "AED (د.إ)", value: "AED" },
  { label: "AFN (؋)", value: "AFN" },
  { label: "ALL (L)", value: "ALL" },
  { label: "AMD (֏)", value: "AMD" },
  { label: "ANG (ƒ)", value: "ANG" },
  { label: "AOA (Kz)", value: "AOA" },
  { label: "ARS ($)", value: "ARS" },
  { label: "AUD (A$)", value: "AUD" },
  { label: "AWG (ƒ)", value: "AWG" },
  { label: "AZN (₼)", value: "AZN" },
  { label: "BAM (KM)", value: "BAM" },
  { label: "BBD (Bds$)", value: "BBD" },
  { label: "BDT (৳)", value: "BDT" },
  { label: "BGN (лв)", value: "BGN" },
  { label: "BHD (.د.ب)", value: "BHD" },
  { label: "BIF (FBu)", value: "BIF" },
  { label: "BMD ($)", value: "BMD" },
  { label: "BND (B$)", value: "BND" },
  { label: "BOB (Bs.)", value: "BOB" },
  { label: "BOV (Mvdol)", value: "BOV" },
  { label: "BRL (R$)", value: "BRL" },
  { label: "BSD (B$)", value: "BSD" },
  { label: "BTN (Nu.)", value: "BTN" },
  { label: "BWP (P)", value: "BWP" },
  { label: "BYR (Br)", value: "BYR" },
  { label: "BZD (BZ$)", value: "BZD" },
  { label: "CAD (C$)", value: "CAD" },
  { label: "CDF (CF)", value: "CDF" },
  { label: "CHE (€)", value: "CHE" },
  { label: "CHF (Fr.)", value: "CHF" },
  { label: "CHW (WIR)", value: "CHW" },
  { label: "CLF (UF)", value: "CLF" },
  { label: "CLP ($)", value: "CLP" },
  { label: "CNY (¥)", value: "CNY" },
  { label: "COP ($)", value: "COP" },
  { label: "COU (COU)", value: "COU" },
  { label: "CRC (₡)", value: "CRC" },
  { label: "CUP (₱)", value: "CUP" },
  { label: "CVE ($)", value: "CVE" },
  { label: "CYP (Cy)", value: "CYP" },
  { label: "CZK (Kč)", value: "CZK" },
  { label: "DJF (Fdj)", value: "DJF" },
  { label: "DKK (kr)", value: "DKK" },
  { label: "DOP (RD$)", value: "DOP" },
  { label: "DZD (دج)", value: "DZD" },
  { label: "EEK (K)", value: "EEK" },
  { label: "EGP (£)", value: "EGP" },
  { label: "ERN (Nfa)", value: "ERN" },
  { label: "ETB (Br)", value: "ETB" },
  { label: "EUR (€)", value: "EUR" },
  { label: "FJD (FJ$)", value: "FJD" },
  { label: "FKP (£)", value: "FKP" },
  { label: "GBP (£)", value: "GBP" },
  { label: "GEL (₾)", value: "GEL" },
  { label: "GHC (GH₵)", value: "GHC" },
  { label: "GIP (£)", value: "GIP" },
  { label: "GMD (D)", value: "GMD" },
  { label: "GNF (FG)", value: "GNF" },
  { label: "GTQ (Q)", value: "GTQ" },
  { label: "GYD (GY$)", value: "GYD" },
  { label: "HKD (HK$)", value: "HKD" },
  { label: "HNL (L)", value: "HNL" },
  { label: "HRK (kn)", value: "HRK" },
  { label: "HTG (G)", value: "HTG" },
  { label: "HUF (Ft)", value: "HUF" },
  { label: "IDR (Rp)", value: "IDR" },
  { label: "ILS (₪)", value: "ILS" },
  { label: "INR (₹)", value: "INR" },
  { label: "IQD (ع.د)", value: "IQD" },
  { label: "IRR (﷼)", value: "IRR" },
  { label: "ISK (kr)", value: "ISK" },
  { label: "JMD (J$)", value: "JMD" },
  { label: "JOD (JD)", value: "JOD" },
  { label: "JPY (¥)", value: "JPY" },
  { label: "KES (KSh)", value: "KES" },
  { label: "KGS (лв)", value: "KGS" },
  { label: "KHR (៛)", value: "KHR" },
  { label: "KMF (CF)", value: "KMF" },
  { label: "KPW (₩)", value: "KPW" },
  { label: "KRW (₩)", value: "KRW" },
  { label: "KWD (د.ك)", value: "KWD" },
  { label: "KYD (KY$)", value: "KYD" },
  { label: "KZT (₸)", value: "KZT" },
  { label: "LAK (₭)", value: "LAK" },
  { label: "LBP (ل.ل)", value: "LBP" },
  { label: "LKR (Rs)", value: "LKR" },
  { label: "LRD (L$)", value: "LRD" },
  { label: "LSL (M)", value: "LSL" },
  { label: "LTL (Lt)", value: "LTL" },
  { label: "LVL (L)", value: "LVL" },
  { label: "LYD (ل.د)", value: "LYD" },
  { label: "MAD (د.م.)", value: "MAD" },
  { label: "MDL (L)", value: "MDL" },
  { label: "MGA (Ar)", value: "MGA" },
  { label: "MKD (ден)", value: "MKD" },
  { label: "MMK (K)", value: "MMK" },
  { label: "MNT (₮)", value: "MNT" },
  { label: "MOP (P)", value: "MOP" },
  { label: "MRO (UM)", value: "MRO" },
  { label: "MTL (MT)", value: "MTL" },
  { label: "MUR (Rs)", value: "MUR" },
  { label: "MVR (Rf)", value: "MVR" },
  { label: "MWK (MK)", value: "MWK" },
  { label: "MXN (MX$)", value: "MXN" },
  { label: "MXV (UDI)", value: "MXV" },
  { label: "MYR (RM)", value: "MYR" },
  { label: "MZN (MT)", value: "MZN" },
  { label: "NAD (N$)", value: "NAD" },
  { label: "NGN (₦)", value: "NGN" },
  { label: "NIO (C$)", value: "NIO" },
  { label: "NOK (kr)", value: "NOK" },
  { label: "NPR (Rs)", value: "NPR" },
  { label: "NZD (NZ$)", value: "NZD" },
  { label: "OMR (ر.ع.)", value: "OMR" },
  { label: "PAB (B/.)", value: "PAB" },
  { label: "PEN (S/.)", value: "PEN" },
  { label: "PGK (K)", value: "PGK" },
  { label: "PHP (₱)", value: "PHP" },
  { label: "PKR (₨)", value: "PKR" },
  { label: "PLN (zł)", value: "PLN" },
  { label: "PYG (₲)", value: "PYG" },
  { label: "QAR (ر.ق)", value: "QAR" },
  { label: "ROL (ROL)", value: "ROL" },
  { label: "RON (lei)", value: "RON" },
  { label: "RSD (дин)", value: "RSD" },
  { label: "RUB (₽)", value: "RUB" },
  { label: "RWF (FRw)", value: "RWF" },
  { label: "SAR (ر.س)", value: "SAR" },
  { label: "SBD (SI$)", value: "SBD" },
  { label: "SCR (SR)", value: "SCR" },
  { label: "SDD (SDD)", value: "SDD" },
  { label: "SEK (kr)", value: "SEK" },
  { label: "SGD (S$)", value: "SGD" },
  { label: "SHP (£)", value: "SHP" },
  { label: "SKK (SKK)", value: "SKK" },
  { label: "SIT (SIT)", value: "SIT" },
  { label: "SLL (Le)", value: "SLL" },
  { label: "SOS (S)", value: "SOS" },
  { label: "SRD ($)", value: "SRD" },
  { label: "STD (STD)", value: "STD" },
  { label: "SYP (£)", value: "SYP" },
  { label: "SZL (E)", value: "SZL" },
  { label: "THB (฿)", value: "THB" },
  { label: "TJS (SM)", value: "TJS" },
  { label: "TMM (TMM)", value: "TMM" },
  { label: "TND (د.ت)", value: "TND" },
  { label: "TOP (T$)", value: "TOP" },
  { label: "TRY (₺)", value: "TRY" },
  { label: "TTD (TT$)", value: "TTD" },
  { label: "TWD (NT$)", value: "TWD" },
  { label: "TZS (TZS)", value: "TZS" },
  { label: "UAH (₴)", value: "UAH" },
  { label: "UGX (USh)", value: "UGX" },
  { label: "USD ($)", value: "USD" },
  { label: "USN (USN)", value: "USN" },
  { label: "USS (USS)", value: "USS" },
  { label: "UYU (UYU)", value: "UYU" },
  { label: "UZS (UZS)", value: "UZS" },
  { label: "VES (Bs.)", value: "VES" },
  { label: "VND (₫)", value: "VND" },
  { label: "VUV (VT)", value: "VUV" },
  { label: "WST (WS$)", value: "WST" },
  { label: "XAF (FCFA)", value: "XAF" },
  { label: "XAG (XAG)", value: "XAG" },
  { label: "XAU (XAU)", value: "XAU" },
  { label: "XBA (XBA)", value: "XBA" },
  { label: "XBB (XBB)", value: "XBB" },
  { label: "XBC (XBC)", value: "XBC" },
  { label: "XBD (XBD)", value: "XBD" },
  { label: "XCD (EC$)", value: "XCD" },
  { label: "XDR (XDR)", value: "XDR" },
  { label: "XFO (XFO)", value: "XFO" },
  { label: "XFU (XFU)", value: "XFU" },
  { label: "XOF (CFA)", value: "XOF" },
  { label: "XPD (XPD)", value: "XPD" },
  { label: "XPF (CFP)", value: "XPF" },
  { label: "XPF (XPF)", value: "XPF" },
  { label: "XPT (XPT)", value: "XPT" },
  { label: "XTS (XTS)", value: "XTS" },
  { label: "XXX (XXX)", value: "XXX" },
  { label: "YER (YER)", value: "YER" },
  { label: "ZAR (R)", value: "ZAR" },
  { label: "ZMK (ZK)", value: "ZMK" },
  { label: "ZWD (Z$)", value: "ZWD" }
];

// Currency locale options for formatting (language-region codes)
// These determine how numbers are formatted (decimal separator, thousands separator, symbol placement)
export const currencyLocaleOptions = [
  { label: "Afrikaans (af)", value: "af" },
  { label: "Afrikaans (af-NA)", value: "af-NA" },
  { label: "Afrikaans (af-ZA)", value: "af-ZA" },
  { label: "Akan (ak)", value: "ak" },
  { label: "Akan (ak-GH)", value: "ak-GH" },
  { label: "Amharic (am)", value: "am" },
  { label: "Amharic (am-ET)", value: "am-ET" },
  { label: "Arabic (ar)", value: "ar" },
  { label: "Arabic (ar-DZ)", value: "ar-DZ" },
  { label: "Arabic (ar-BH)", value: "ar-BH" },
  { label: "Arabic (ar-TD)", value: "ar-TD" },
  { label: "Arabic (ar-KM)", value: "ar-KM" },
  { label: "Arabic (ar-DJ)", value: "ar-DJ" },
  { label: "Arabic (ar-EG)", value: "ar-EG" },
  { label: "Arabic (ar-EM)", value: "ar-EM" },
  { label: "Arabic (ar-IQ)", value: "ar-IQ" },
  { label: "Arabic (ar-IL)", value: "ar-IL" },
  { label: "Arabic (ar-JO)", value: "ar-JO" },
  { label: "Arabic (ar-KW)", value: "ar-KW" },
  { label: "Arabic (ar-LB)", value: "ar-LB" },
  { label: "Arabic (ar-LY)", value: "ar-LY" },
  { label: "Arabic (ar-MR)", value: "ar-MR" },
  { label: "Arabic (ar-MA)", value: "ar-MA" },
  { label: "Arabic (ar-OM)", value: "ar-OM" },
  { label: "Arabic (ar-PS)", value: "ar-PS" },
  { label: "Arabic (ar-QA)", value: "ar-QA" },
  { label: "Arabic (ar-SA)", value: "ar-SA" },
  { label: "Arabic (ar-SO)", value: "ar-SO" },
  { label: "Arabic (ar-SS)", value: "ar-SS" },
  { label: "Arabic (ar-SD)", value: "ar-SD" },
  { label: "Arabic (ar-SY)", value: "ar-SY" },
  { label: "Arabic (ar-TN)", value: "ar-TN" },
  { label: "Arabic (ar-AE)", value: "ar-AE" },
  { label: "Arabic (ar-0001)", value: "ar-0001" },
  { label: "Arabic (ar-YE)", value: "ar-YE" },
  { label: "Azerbaijani Cyrillic (az-Cyrl)", value: "az-Cyrl" },
  { label: "Azerbaijani Latin (az-Latn)", value: "az-Latn" },
  { label: "Azerbaijani Cyrillic (az-Cyrl-AZ)", value: "az-Cyrl-AZ" },
  { label: "Azerbaijani Latin (az-Latn-AZ)", value: "az-Latn-AZ" },
  { label: "Bangla (bn)", value: "bn" },
  { label: "Bangla (bn-BD)", value: "bn-BD" },
  { label: "Bangla (bn-IN)", value: "bn-IN" },
  { label: "Bosnian Cyrillic (bs-Cyrl)", value: "bs-Cyrl" },
  { label: "Bosnian Latin (bs-Latn)", value: "bs-Latn" },
  { label: "Bosnian (bs)", value: "bs" },
  { label: "Bosnian Cyrillic (bs-Cyrl-BA)", value: "bs-Cyrl-BA" },
  { label: "Bosnian Latin (bs-Latn-BA)", value: "bs-Latn-BA" },
  { label: "Bulgarian (bg)", value: "bg" },
  { label: "Bulgarian (bg-BG)", value: "bg-BG" },
  { label: "Catalan (ca)", value: "ca" },
  { label: "Catalan (ca-AD)", value: "ca-AD" },
  { label: "Catalan (ca-FR)", value: "ca-FR" },
  { label: "Catalan (ca-IT)", value: "ca-IT" },
  { label: "Catalan (ca-ES)", value: "ca-ES" },
  { label: "Chinese (zh)", value: "zh" },
  { label: "Chinese (zh-CN)", value: "zh-CN" },
  { label: "Chinese (zh-SG)", value: "zh-SG" },
  { label: "Chinese (zh-TW)", value: "zh-TW" },
  { label: "Chinese (zh-HK)", value: "zh-HK" },
  { label: "Chinese (zh-MO)", value: "zh-MO" },
  { label: "Chinese (zh-Hans)", value: "zh-Hans" },
  { label: "Chinese (zh-Hant)", value: "zh-Hant" },
  { label: "Congo Swahili (swc)", value: "swc" },
  { label: "Congo Swahili (swc-CD)", value: "swc-CD" },
  { label: "Croatian (hr)", value: "hr" },
  { label: "Croatian (hr-HR)", value: "hr-HR" },
  { label: "Croatian (hr-BA)", value: "hr-BA" },
  { label: "Czech (cs)", value: "cs" },
  { label: "Czech (cs-CZ)", value: "cs-CZ" },
  { label: "Danish (da)", value: "da" },
  { label: "Danish (da-DK)", value: "da-DK" },
  { label: "Danish (da-GL)", value: "da-GL" },
  { label: "Dari (prs)", value: "prs" },
  { label: "Dari (prs-AF)", value: "prs-AF" },
  { label: "Dutch (nl)", value: "nl" },
  { label: "Dutch (nl-AW)", value: "nl-AW" },
  { label: "Dutch (nl-NL)", value: "nl-NL" },
  { label: "Dutch (nl-BE)", value: "nl-BE" },
  { label: "Dutch (nl-BQ)", value: "nl-BQ" },
  { label: "Dutch (nl-CW)", value: "nl-CW" },
  { label: "Dutch (nl-SR)", value: "nl-SR" },
  { label: "Dutch (nl-SX)", value: "nl-SX" },
  { label: "English (en)", value: "en" },  
  { label: "English (en-AS)", value: "en-AS" },
  { label: "English (en-AI)", value: "en-AI" },
  { label: "English (en-AG)", value: "en-AG" },
  { label: "English (en-AU)", value: "en-AU" },
  { label: "English (en-AT)", value: "en-AT" },
  { label: "English (en-BS)", value: "en-BS" },
  { label: "English (en-BB)", value: "en-BB" },
  { label: "English (en-BE)", value: "en-BE" },
  { label: "English (en-BZ)", value: "en-BZ" },
  { label: "English (en-BM)", value: "en-BM" },
  { label: "English (en-BW)", value: "en-BW" },
  { label: "English (en-IO)", value: "en-IO" },
  { label: "English (en-VG)", value: "en-VG" },
  { label: "English (en-BI)", value: "en-BI" },
  { label: "English (en-CM)", value: "en-CM" },
  { label: "English (en-CA)", value: "en-CA" },
  { label: "English (en-029)", value: "en-029" },
  { label: "English (en-KY)", value: "en-KY" },
  { label: "English (en-CX)", value: "en-CX" },
  { label: "English (en-CC)", value: "en-CC" },
  { label: "English (en-CK)", value: "en-CK" },
  { label: "English (en-CY)", value: "en-CY" },
  { label: "English (en-DK)", value: "en-DK" },
  { label: "English (en-DM)", value: "en-DM" },
  { label: "English (en-ER)", value: "en-ER" },
  { label: "English (en-150)", value: "en-150" },
  { label: "English (en-FK)", value: "en-FK" },
  { label: "English (en-FI)", value: "en-FI" },
  { label: "English (en-FJ)", value: "en-FJ" },
  { label: "English (en-GM)", value: "en-GM" },
  { label: "English (en-DE)", value: "en-DE" },
  { label: "English (en-GH)", value: "en-GH" },
  { label: "English (en-GI)", value: "en-GI" },
  { label: "English (en-GD)", value: "en-GD" },
  { label: "English (en-GU)", value: "en-GU" },
  { label: "English (en-GG)", value: "en-GG" },
  { label: "English (en-GY)", value: "en-GY" },
  { label: "English (en-HK)", value: "en-HK" },
  { label: "English (en-IN)", value: "en-IN" },
  { label: "English (en-IE)", value: "en-IE" },
  { label: "English (en-IM)", value: "en-IM" },
  { label: "English (en-IL)", value: "en-IL" },
  { label: "English (en-JM)", value: "en-JM" },
  { label: "English (en-JE)", value: "en-JE" },
  { label: "English (en-KE)", value: "en-KE" },
  { label: "English (en-KI)", value: "en-KI" },
  { label: "English (en-LS)", value: "en-LS" },
  { label: "English (en-LR)", value: "en-LR" },
  { label: "English (en-MG)", value: "en-MG" },
  { label: "English (en-MO)", value: "en-MO" },
  { label: "English (en-MW)", value: "en-MW" },
  { label: "English (en-MY)", value: "en-MY" },
  { label: "English (en-MH)", value: "en-MH" },
  { label: "English (en-MT)", value: "en-MT" },
  { label: "English (en-MU)", value: "en-MU" },
  { label: "English (en-FM)", value: "en-FM" },
  { label: "English (en-MS)", value: "en-MS" },
  { label: "English (en-NA)", value: "en-NA" },
  { label: "English (en-NR)", value: "en-NR" },
  { label: "English (en-NL)", value: "en-NL" },
  { label: "English (en-NZ)", value: "en-NZ" },
  { label: "English (en-NG)", value: "en-NG" },
  { label: "English (en-NU)", value: "en-NU" },
  { label: "English (en-NF)", value: "en-NF" },
  { label: "English (en-MP)", value: "en-MP" },
  { label: "English (en-PK)", value: "en-PK" },
  { label: "English (en-PW)", value: "en-PW" },
  { label: "English (en-PG)", value: "en-PG" },
  { label: "English (en-PN)", value: "en-PN" },
  { label: "English (en-PR)", value: "en-PR" },
  { label: "English (en-PH)", value: "en-PH" },
  { label: "English (en-RW)", value: "en-RW" },
  { label: "English (en-KN)", value: "en-KN" },
  { label: "English (en-LC)", value: "en-LC" },
  { label: "English (en-VC)", value: "en-VC" },
  { label: "English (en-WS)", value: "en-WS" },
  { label: "English (en-SC)", value: "en-SC" },
  { label: "English (en-SG)", value: "en-SG" },
  { label: "English (en-SL)", value: "en-SL" },
  { label: "English (en-SX)", value: "en-SX" },
  { label: "English (en-SZ)", value: "en-SZ" },
  { label: "English (en-SI)", value: "en-SI" },
  { label: "English (en-SB)", value: "en-SB" },
  { label: "English (en-ZA)", value: "en-ZA" },
  { label: "English (en-SS)", value: "en-SS" },
  { label: "English (en-SH)", value: "en-SH" },
  { label: "English (en-SD)", value: "en-SD" },
  { label: "English (en-CH)", value: "en-CH" },
  { label: "English (en-SZ)", value: "en-SZ" },
  { label: "English (en-SE)", value: "en-SE" },
  { label: "English (en-TZ)", value: "en-TZ" },
  { label: "English (en-TK)", value: "en-TK" },
  { label: "English (en-TO)", value: "en-TO" },
  { label: "English (en-TT)", value: "en-TT" },
  { label: "English (en-TC)", value: "en-TC" },
  { label: "English (en-TV)", value: "en-TV" },
  { label: "English (en-UG)", value: "en-UG" },
  { label: "English (en-AE)", value: "en-AE" },
  { label: "English (en-GB)", value: "en-GB" },
  { label: "English (en-US)", value: "en-US" },
  { label: "English (en-UM)", value: "en-UM" },
  { label: "English (en-VI)", value: "en-VI" },
  { label: "English (en-UV)", value: "en-UV" },
  { label: "English (en-001)", value: "en-001" },
  { label: "English (en-ZM)", value: "en-ZM" },
  { label: "English (en-ZW)", value: "en-ZW" },
  { label: "Estonian (et)", value: "et" },
  { label: "Estonian (et-EE)", value: "et-EE" },
  { label: "Filipino (fil)", value: "fil" },
  { label: "Filipino (fil-PH)", value: "fil-PH" },
  { label: "Finnish (fi)", value: "fi" },
  { label: "Finnish (fi-FI)", value: "fi-FI" },
  { label: "French (fr)", value: "fr" },
  { label: "French (fr-DZ)", value: "fr-DZ" },
  { label: "French (fr-BE)", value: "fr-BE" },
  { label: "French (fr-BJ)", value: "fr-BJ" },
  { label: "French (fr-BF)", value: "fr-BF" },
  { label: "French (fr-BI)", value: "fr-BI" },
  { label: "French (fr-CM)", value: "fr-CM" },
  { label: "French (fr-CA)", value: "fr-CA" },
  { label: "French (fr-CF)", value: "fr-CF" },
  { label: "French (fr-TD)", value: "fr-TD" },
  { label: "French (fr-KM)", value: "fr-KM" },
  { label: "French (fr-CG)", value: "fr-CG" },
  { label: "French (fr-CD)", value: "fr-CD" },
  { label: "French (fr-CI)", value: "fr-CI" },
  { label: "French (fr-DJ)", value: "fr-DJ" },
  { label: "French (fr-GQ)", value: "fr-GQ" },
  { label: "French (fr-FR)", value: "fr-FR" },
  { label: "French (fr-GF)", value: "fr-GF" },
  { label: "French (fr-PF)", value: "fr-PF" },
  { label: "French (fr-GA)", value: "fr-GA" },
  { label: "French (fr-GP)", value: "fr-GP" },
  { label: "French (fr-GN)", value: "fr-GN" },
  { label: "French (fr-HT)", value: "fr-HT" },
  { label: "French (fr-LU)", value: "fr-LU" },
  { label: "French (fr-MG)", value: "fr-MG" },
  { label: "French (fr-ML)", value: "fr-ML" },
  { label: "French (fr-MQ)", value: "fr-MQ" },
  { label: "French (fr-MR)", value: "fr-MR" },
  { label: "French (fr-MU)", value: "fr-MU" },
  { label: "French (fr-YT)", value: "fr-YT" },
  { label: "French (fr-MA)", value: "fr-MA" },
  { label: "French (fr-NC)", value: "fr-NC" },
  { label: "French (fr-ME)", value: "fr-ME" },
  { label: "French (fr-MC)", value: "fr-MC" },
  { label: "French (fr-RE)", value: "fr-RE" },
  { label: "French (fr-RW)", value: "fr-RW" },
  { label: "French (fr-BL)", value: "fr-BL" },
  { label: "French (fr-MF)", value: "fr-MF" },
  { label: "French (fr-PM)", value: "fr-PM" },
  { label: "French (fr-SN)", value: "fr-SN" },
  { label: "French (fr-SC)", value: "fr-SC" },
  { label: "French (fr-SY)", value: "fr-SY" },
  { label: "French (fr-CH)", value: "fr-CH" },
  { label: "French (fr-TG)", value: "fr-TG" },
  { label: "French (fr-TN)", value: "fr-TN" },
  { label: "French (fr-VU)", value: "fr-VU" },
  { label: "French (fr-WF)", value: "fr-WF" },
  { label: "German (de)", value: "de" },
  { label: "German (de-BE)", value: "de-BE" },
  { label: "German (de-AT)", value: "de-AT" },
  { label: "German (de-DE)", value: "de-DE" },
  { label: "German (de-IT)", value: "de-IT" },
  { label: "German (de-LI)", value: "de-LI" },
  { label: "German (de-LU)", value: "de-LU" },
  { label: "German (de-CH)", value: "de-CH" },
  { label: "Greek (el)", value: "el" },
  { label: "Greek (el-GR)", value: "el-GR" },
  { label: "Greek (el-CY)", value: "el-CY" },
  { label: "Gujarati (gu)", value: "gu" },
  { label: "Gujarati (gu-IN)", value: "gu-IN" },
  { label: "Hebrew (he)", value: "he" },
  { label: "Hebrew (he-IL)", value: "he-IL" },
  { label: "Hindi (hi)", value: "hi" },
  { label: "Hindi (hi-IN)", value: "hi-IN" },
  { label: "Hungarian (hu)", value: "hu" },
  { label: "Hungarian (hu-HU)", value: "hu-HU" },
  { label: "Indonesian (id)", value: "id" },
  { label: "Indonesian (id-ID)", value: "id-ID" },
  { label: "Italian (it)", value: "it" },
  { label: "Italian (it-IT)", value: "it-IT" },
  { label: "Italian (it-CH)", value: "it-CH" },
  { label: "Italian (it-SM)", value: "it-SM" },
  { label: "Italian (it-VA)", value: "it-VA" },
  { label: "Japanese (ja)", value: "ja" },
  { label: "Japanese (ja-JP)", value: "ja-JP" },
  { label: "Kannada (kn)", value: "kn" },
  { label: "Kannada (kn-IN)", value: "kn-IN" },
  { label: "Kiswahili (sw)", value: "sw" },
  { label: "Kiswahili (sw-KE)", value: "sw-KE" },
  { label: "Kiswahili (sw-TZ)", value: "sw-TZ" },
  { label: "Kiswahili (sw-UG)", value: "sw-UG" },
  { label: "Korean (ko)", value: "ko" },
  { label: "Korean (ko-KR)", value: "ko-KR" },
  { label: "Korean (ko-KP)", value: "ko-KP" },
  { label: "Latvian (lv)", value: "lv" },
  { label: "Latvian (lv-LV)", value: "lv-LV" },
  { label: "Lithuanian (lt)", value: "lt" },
  { label: "Lithuanian (lt-LT)", value: "lt-LT" },
  { label: "Malay (ms)", value: "ms" },
  { label: "Malay (ms-MY)", value: "ms-MY" },
  { label: "Malay (ms-BN)", value: "ms-BN" },
  { label: "Malay (ms-Latn)", value: "ms-Latn" },
  { label: "Malayalam (ml)", value: "ml" },
  { label: "Malayalam (ml-IN)", value: "ml-IN" },
  { label: "Marathi (mr)", value: "mr" },
  { label: "Marathi (mr-IN)", value: "mr-IN" },
  { label: "Norwegian (no)", value: "no" },
  { label: "Norwegian (no-NO)", value: "no-NO" },
  { label: "Norwegian (nb)", value: "nb" },
  { label: "Norwegian (nb-SJ)", value: "nb-SJ" },
  { label: "Persian (fa)", value: "fa" },
  { label: "Persian (fa-IR)", value: "fa-IR" },
  { label: "Persian (fa-AF)", value: "fa-AF" },
  { label: "Polish (pl)", value: "pl" },
  { label: "Polish (pl-PL)", value: "pl-PL" },
  { label: "Portuguese (pt)", value: "pt" },
  { label: "Portuguese (pt-BR)", value: "pt-BR" },
  { label: "Portuguese (pt-CV)", value: "pt-CV" },
  { label: "Portuguese (pt-AO)", value: "pt-AO" },
  { label: "Portuguese (pt-GQ)", value: "pt-GQ" },
  { label: "Portuguese (pt-GW)", value: "pt-GW" },
  { label: "Portuguese (pt-LU)", value: "pt-LU" },
  { label: "Portuguese (pt-MO)", value: "pt-MO" },
  { label: "Portuguese (pt-MZ)", value: "pt-MZ" },
  { label: "Portuguese (pt-PT)", value: "pt-PT" },
  { label: "Portuguese (pt-ST)", value: "pt-ST" },
  { label: "Portuguese (pt-CH)", value: "pt-CH" },
  { label: "Portuguese (pt-TL)", value: "pt-TL" },
  { label: "Punjabi (pa)", value: "pa" },
  { label: "Punjabi (pa-IN)", value: "pa-IN" },
  { label: "Punjabi (pa-Arab)", value: "pa-Arab" },
  { label: "Punjabi (pa-Arab-PAK)", value: "pa-Arab-PAK" },
  { label: "Romanian (ro)", value: "ro" },
  { label: "Romanian (ro-RO)", value: "ro-RO" },
  { label: "Romanian (ro-MD)", value: "ro-MD" },
  { label: "Russian (ru)", value: "ru" },
  { label: "Russian (ru-RU)", value: "ru-RU" },
  { label: "Russian (ru-BY)", value: "ru-BY" },
  { label: "Russian (ru-KZ)", value: "ru-KZ" },
  { label: "Russian (ru-KG)", value: "ru-KG" },
  { label: "Russian (ru-MD)", value: "ru-MD" },
  { label: "Russian (ru-UA)", value: "ru-UA" },
  { label: "Serbian (sr-Cyrl)", value: "sr-Cyrl" },
  { label: "Serbian (sr-Cyrl-BA)", value: "sr-Cyrl-BA" },
  { label: "Serbian (sr-Cyrl-ME)", value: "sr-Cyrl-ME" },
  { label: "Serbian (sr-Cyrl-RS)", value: "sr-Cyrl-RS" },
  { label: "Serbian (sr-Cyrl-CS)", value: "sr-Cyrl-CS" },
  { label: "Serbian (sr)", value: "sr" },
  { label: "Serbian (sr-Latn)", value: "sr-Latn" },
  { label: "Serbian (sr-Latn-BA)", value: "sr-Latn-BA" },
  { label: "Serbian (sr-Latn-ME)", value: "sr-Latn-ME" },
  { label: "Serbian (sr-Latn-RS)", value: "sr-Latn-RS" },
  { label: "Serbian (sr-Latn-CS)", value: "sr-Latn-CS" },
  { label: "Slovak (sk)", value: "sk" },
  { label: "Slovak (sk-SK)", value: "sk-SK" },
  { label: "Slovenian (sl)", value: "sl" },
  { label: "Slovenian (sl-SI)", value: "sl-SI" },
  { label: "Spanish (es)", value: "es" },
  { label: "Spanish (es-AR)", value: "es-AR" },
  { label: "Spanish (es-BZ)", value: "es-BZ" },
  { label: "Spanish (es-VE)", value: "es-VE" },
  { label: "Spanish (es-BO)", value: "es-BO" },
  { label: "Spanish (es-BR)", value: "es-BR" },
  { label: "Spanish (es-CL)", value: "es-CL" },
  { label: "Spanish (es-CO)", value: "es-CO" },
  { label: "Spanish (es-CR)", value: "es-CR" },
  { label: "Spanish (es-CU)", value: "es-CU" },
  { label: "Spanish (es-DO)", value: "es-DO" },
  { label: "Spanish (es-EC)", value: "es-EC" },
  { label: "Spanish (es-SV)", value: "es-SV" },
  { label: "Spanish (es-GQ)", value: "es-GQ" },
  { label: "Spanish (es-GT)", value: "es-GT" },
  { label: "Spanish (es-HN)", value: "es-HN" },
  { label: "Spanish (es-419)", value: "es-419" },
  { label: "Spanish (es-MX)", value: "es-MX" },
  { label: "Spanish (es-NI)", value: "es-NI" },
  { label: "Spanish (es-PA)", value: "es-PA" },
  { label: "Spanish (es-PY)", value: "es-PY" },
  { label: "Spanish (es-PE)", value: "es-PE" },
  { label: "Spanish (es-PH)", value: "es-PH" },
  { label: "Spanish (es-PR)", value: "es-PR" },
  { label: "Spanish (es-ES)", value: "es-ES" },
  { label: "Spanish (es-US)", value: "es-US" },
  { label: "Spanish (es-UY)", value: "es-UY" },
  { label: "Swedish (sv)", value: "sv" },
  { label: "Swedish (sv-SE)", value: "sv-SE" },
  { label: "Swedish (sv-FI)", value: "sv-FI" },
  { label: "Swedish (sv-AX)", value: "sv-AX" },
  { label: "Tamil (ta)", value: "ta" },
  { label: "Tamil (ta-IN)", value: "ta-IN" },
  { label: "Tamil (ta-MY)", value: "ta-MY" },
  { label: "Tamil (ta-SG)", value: "ta-SG" },
  { label: "Tamil (ta-LK)", value: "ta-LK" },
  { label: "Telugu (te)", value: "te" },
  { label: "Telugu (te-IN)", value: "te-IN" },
  { label: "Thai (th)", value: "th" },
  { label: "Thai (th-TH)", value: "th-TH" },
  { label: "Turkish (tr)", value: "tr" },
  { label: "Turkish (tr-TR)", value: "tr-TR" },
  { label: "Turkish (tr-CY)", value: "tr-CY" },
  { label: "Ukrainian (uk)", value: "uk" },
  { label: "Ukrainian (uk-UA)", value: "uk-UA" },
  { label: "Urdu (ur)", value: "ur" },
  { label: "Urdu (ur-PK)", value: "ur-PK" },
  { label: "Uzbek (uz-Arab)", value: "uz-Arab" },
  { label: "Uzbek (uz-Arab-AF)", value: "uz-Arab-AF" },
  { label: "Uzbek (uz-cyrl)", value: "uz-cyrl" },
  { label: "Uzbek (uz-cyrl-UZ)", value: "uz-cyrl-UZ" },
  { label: "Uzbek (uz)", value: "uz" },
  { label: "Uzbek (uz-Latn)", value: "uz-Latn" },
  { label: "Uzbek (uz-Latn-UZ)", value: "uz-Latn-UZ" },
  { label: "Vietnamese (vi)", value: "vi" },
  { label: "Vietnamese (vi-VN)", value: "vi-VN" },
  { label: "Yoruba (yo-BJ)", value: "yo-BJ" },
];

// defined progress color options
export const progressColorOptions = [
  { label: "Blue", value: "blue" },
  { label: "Green", value: "green" },
  { label: "Yellow", value: "yellow" },
  { label: "Orange", value: "orange" },
  { label: "Red", value: "red" },
  { label: "Purple", value: "purple" },
  { label: "Pink", value: "pink" },
  { label: "Indigo", value: "indigo" },
  { label: "Teal", value: "teal" },
];

// defined duration format options
export const durationFormatOptions = [
  { label: "h:mm", value: "h:mm" },
  { label: "h:mm:ss", value: "h:mm:ss" },
  { label: "h:mm:ss.s", value: "h:mm:ss.s" },
  { label: "h:mm:ss.ss", value: "h:mm:ss.ss" },
  { label: "h:mm:ss.sss", value: "h:mm:ss.sss" },
];

// defined date format options
export const dateFormatOptions = [
  { label: "YYYY-MM-DD", value: "YYYY-MM-DD" },
  { label: "YYYY/MM/DD", value: "YYYY/MM/DD" },
  { label: "DD-MM-YYYY", value: "DD-MM-YYYY" },
  { label: "MM-DD-YYYY", value: "MM-DD-YYYY" },
  { label: "DD/MM/YYYY", value: "DD/MM/YYYY" },
  { label: "MM/DD/YYYY", value: "MM/DD/YYYY" },
  { label: "DD MM YYYY", value: "DD MM YYYY" },
];

// defined time format options
export const timeFormatOptions = [
  { label: "hh:mm", value: "hh:mm" },
  { label: "hh:mm:ss", value: "hh:mm:ss" },
  { label: "hh:mm:ss.SSS", value: "hh:mm:ss.SSS" },
];


// defined link text options
export const linkTextOptions = [
  { label: "Show URL", value: "url" },
  { label: "Custom text", value: "custom" },
  { label: "Show domain only", value: "domain" }
];

// defined source table options
export const sourceTableOptions = [
  { label: "Select a table", value: "" },
  { label: "Users", value: "users" },
  { label: "Products", value: "products" },
  { label: "Orders", value: "orders" }
];

// defined display field options
export const displayFieldOptions = [
  { label: "Select display field", value: "" },
  { label: "Name", value: "name" },
  { label: "Title", value: "title" },
  { label: "ID", value: "id" }
];


export const ratingColorOptions = [
  { key: 'yellow', label: 'Yellow', className: 'text-yellow-400', color: '#fbbf24' },
  { key: 'blue', label: 'Blue', className: 'text-blue-400', color: '#60a5fa' },
  { key: 'red', label: 'Red', className: 'text-red-400', color: '#f87171' },
  { key: 'green', label: 'Green', className: 'text-green-400', color: '#4ade80' },
  { key: 'purple', label: 'Purple', className: 'text-purple-400', color: '#a78bfa' },
  { key: 'pink', label: 'Pink', className: 'text-pink-400', color: '#f472b6' },
  { key: 'orange', label: 'Orange', className: 'text-orange-400', color: '#fb923c' },
  { key: 'indigo', label: 'Indigo', className: 'text-indigo-400', color: '#818cf8' },
  { key: 'teal', label: 'Teal', className: 'text-teal-400', color: '#2dd4bf' },
  { key: 'gray', label: 'Gray', className: 'text-gray-400', color: '#9ca3af' },
];

export const timeZoneOptions = [
  { label: "Africa/Abidjan", value: "GMT", country: "Ivory Coast" },
  { label: "Africa/Accra", value: "GMT", country: "Ghana" },
  { label: "Africa/Addis_Ababa", value: "EAT", country: "Ethiopia" },
  { label: "Africa/Algiers", value: "CET", country: "Algeria" },
  { label: "Africa/Asmara", value: "EAT", country: "Eritrea" },
  { label: "Africa/Bamako", value: "GMT", country: "Mali" },
  { label: "Africa/Bangui", value: "WAT", country: "Central African Republic" },
  { label: "Africa/Banjul", value: "GMT", country: "Gambia" },
  { label: "Africa/Bissau", value: "GMT", country: "Guinea-Bissau" },
  { label: "Africa/Blantyre", value: "CAT", country: "Malawi" },
  { label: "Africa/Brazzaville", value: "WAT", country: "Congo" },
  { label: "Africa/Bujumbura", value: "CAT", country: "Burundi" },
  { label: "Africa/Cairo", value: "EET", country: "Egypt" },
  { label: "Africa/Casablanca", value: "WAT", country: "Morocco" },
  { label: "Africa/Conakry", value: "GMT", country: "Guinea" },
  { label: "Africa/Dakar", value: "GMT", country: "Senegal" },
  { label: "Africa/Dar_es_Salaam", value: "EAT", country: "Tanzania" },
  { label: "Africa/Djibouti", value: "EAT", country: "Djibouti" },
  { label: "Africa/Douala", value: "WAT", country: "Cameroon" },
  { label: "Africa/El_Aaiun", value: "WET", country: "Western Sahara" },
  { label: "Africa/Freetown", value: "GMT", country: "Sierra Leone" },
  { label: "Africa/Gaborone", value: "CAT", country: "Botswana" },
  { label: "Africa/Harare", value: "CAT", country: "Zimbabwe" },
  { label: "Africa/Johannesburg", value: "SAST", country: "South Africa" },
  { label: "Africa/Juba", value: "CAT", country: "South Sudan" },
  { label: "Africa/Kampala", value: "EAT", country: "Uganda" },
  { label: "Africa/Khartoum", value: "CAT", country: "Sudan" },
  { label: "Africa/Kigali", value: "CAT", country: "Rwanda" },
  { label: "Africa/Kinshasa", value: "WAT", country: "Congo (Kinshasa)" },
  { label: "Africa/Lagos", value: "WAT", country: "Nigeria" },
  { label: "Africa/Libreville", value: "WAT", country: "Gabon" },
  { label: "Africa/Lome", value: "GMT", country: "Togo" },
  { label: "Africa/Luanda", value: "WAT", country: "Angola" },
  { label: "Africa/Lubumbashi", value: "CAT", country: "Congo (Kinshasa)" },
  { label: "Africa/Lusaka", value: "CAT", country: "Zambia" },
  { label: "Africa/Malabo", value: "WAT", country: "Equatorial Guinea" },
  { label: "Africa/Maputo", value: "CAT", country: "Mozambique" },
  { label: "Africa/Maseru", value: "SAST", country: "Lesotho" },
  { label: "Africa/Mbabane", value: "SAST", country: "Eswatini" },
  { label: "Africa/Mogadishu", value: "EAT", country: "Somalia" },
  { label: "Africa/Monrovia", value: "GMT", country: "Liberia" },
  { label: "Africa/Nairobi", value: "EAT", country: "Kenya" },
  { label: "Africa/Ndjamena", value: "WAT", country: "Chad" },
  { label: "Africa/Niamey", value: "WAT", country: "Niger" },
  { label: "Africa/Nouakchott", value: "GMT", country: "Mauritania" },
  { label: "Africa/Ouagadougou", value: "GMT", country: "Burkina Faso" },
  { label: "Africa/Porto-Novo", value: "WAT", country: "Benin" },
  { label: "Africa/Sao_Tome", value: "GMT", country: "São Tomé and Príncipe" },
  { label: "Africa/Tripoli", value: "EET", country: "Libya" },
  { label: "Africa/Tunis", value: "CET", country: "Tunisia" },
  { label: "Africa/Windhoek", value: "CAT", country: "Namibia" },
  { label: "America/Adak", value: "HAST", country: "United States (Alaska)" },
  { label: "America/Anchorage", value: "AKST", country: "United States (Alaska)" },
  { label: "America/Anguilla", value: "AST", country: "Anguilla" },
  { label: "America/Antigua", value: "AST", country: "Antigua and Barbuda" },
  { label: "America/Argentina/Buenos_Aires", value: "ART", country: "Argentina" },
  { label: "America/Aruba", value: "AST", country: "Aruba" },
  { label: "America/Asuncion", value: "PYT", country: "Paraguay" },
  { label: "America/Atikokan", value: "EST", country: "Canada" },
  { label: "America/Barbados", value: "AST", country: "Barbados" },
  { label: "America/Belize", value: "CST", country: "Belize" },
  { label: "America/Blanc-Sablon", value: "AST", country: "Canada" },
  { label: "America/Bogota", value: "COT", country: "Colombia" },
  { label: "America/Cancun", value: "EST", country: "Mexico" },
  { label: "America/Caracas", value: "VET", country: "Venezuela" },
  { label: "America/Cayenne", value: "GFT", country: "French Guiana" },
  { label: "America/Cayman", value: "EST", country: "Cayman Islands" },
  { label: "America/Chicago", value: "CST", country: "United States" },
  { label: "America/Ciudad_Juarez", value: "MST", country: "Mexico" },
  { label: "America/Costa_Rica", value: "CST", country: "Costa Rica" },
  { label: "America/Curacao", value: "AST", country: "Curaçao" },
  { label: "America/Danmarkshavn", value: "GMT", country: "Greenland" },
  { label: "America/Denver", value: "MST", country: "United States" },
  { label: "America/Dominica", value: "AST", country: "Dominica" },
  { label: "America/Edmonton", value: "MST", country: "Canada" },
  { label: "America/El_Salvador", value: "CST", country: "El Salvador" },
  { label: "America/Grand_Turk", value: "EST", country: "Turks and Caicos Islands" },
  { label: "America/Grenada", value: "AST", country: "Grenada" },
  { label: "America/Guadeloupe", value: "AST", country: "Guadeloupe" },
  { label: "America/Guatemala", value: "CST", country: "Guatemala" },
  { label: "America/Guyana", value: "GYT", country: "Guyana" },
  { label: "America/Halifax", value: "AST", country: "Canada" },
  { label: "America/Havana", value: "CST", country: "Cuba" },
  { label: "America/Hermosillo", value: "GMT-7", country: "Mexico" },
  { label: "America/Jamaica", value: "EST", country: "Jamaica" },
  { label: "America/Kralendijk", value: "AST", country: "Bonaire, Sint Eustatius and Saba" },
  { label: "America/La_Paz", value: "BOT", country: "Bolivia" },
  { label: "America/Lima", value: "PET", country: "Peru" },
  { label: "America/Los_Angeles", value: "PST", country: "United States" },
  { label: "America/Lower_Princes", value: "AST", country: "Sint Maarten" },
  { label: "America/Managua", value: "CST", country: "Nicaragua" },
  { label: "America/Manaus", value: "AMT", country: "Brazil" },
  { label: "America/Marigot", value: "AST", country: "Saint Martin" },
  { label: "America/Martinique", value: "AST", country: "Martinique" },
  { label: "America/Matamoros", value: "CST", country: "Mexico" },
  { label: "America/Mexico_City", value: "CST", country: "Mexico" },
  { label: "America/Miquelon", value: "PMST", country: "Saint Pierre and Miquelon" },
  { label: "America/Montevideo", value: "UYT", country: "Uruguay" },
  { label: "America/Montserrat", value: "AST", country: "Montserrat" },
  { label: "America/Nassau", value: "EST", country: "Bahamas" },
  { label: "America/New_York", value: "EST", country: "United States" },
  { label: "America/Noronha", value: "FNT", country: "Brazil" },
  { label: "America/Nuuk", value: "GMT-2", country: "Greenland" },
  { label: "America/Panama", value: "EST", country: "Panama" },
  { label: "America/Paramaribo", value: "SRT", country: "Suriname" },
  { label: "America/Phoenix", value: "MST", country: "United States" },
  { label: "America/Port_of_Spain", value: "AST", country: "Trinidad and Tobago" },
  { label: "America/Port-au-Prince", value: "EST", country: "Haiti" },
  { label: "America/Puerto_Rico", value: "AST", country: "Puerto Rico" },
  { label: "America/Punta_Arenas", value: "CLT", country: "Chile" },
  { label: "America/Regina", value: "CST", country: "Canada" },
  { label: "America/Rio_Branco", value: "ACT", country: "Brazil" },
  { label: "America/Santiago", value: "CLT", country: "Chile" },
  { label: "America/Santo_Domingo", value: "AST", country: "Dominican Republic" },
  { label: "America/Sao_Paulo", value: "BRT", country: "Brazil" },
  { label: "America/St_Barthelemy", value: "AST", country: "Saint Barthélemy" },
  { label: "America/St_Johns", value: "NST", country: "Canada" },
  { label: "America/St_Kitts", value: "AST", country: "Saint Kitts and Nevis" },
  { label: "America/St_Lucia", value: "AST", country: "Saint Lucia" },
  { label: "America/St_Thomas", value: "AST", country: "U.S. Virgin Islands" },
  { label: "America/St_Vincent", value: "AST", country: "Saint Vincent and the Grenadines" },
  { label: "America/Tegucigalpa", value: "CST", country: "Honduras" },
  { label: "America/Thule", value: "AST", country: "Greenland" },
  { label: "America/Tijuana", value: "PST", country: "Mexico" },
  { label: "America/Toronto", value: "EST", country: "Canada" },
  { label: "America/Tortola", value: "AST", country: "British Virgin Islands" },
  { label: "America/Vancouver", value: "PST", country: "Canada" },
  { label: "America/Whitehorse", value: "YT", country: "Canada" },
  { label: "America/Winnipeg", value: "CST", country: "Canada" },
  { label: "Antarctica/Casey", value: "AWST", country: "Antarctica (Australia)" },
  { label: "Antarctica/Davis", value: "DAVT", country: "Antarctica (Australia)" },
  { label: "Antarctica/DumontDUrville", value: "GMT+10", country: "Antarctica (France)" },
  { label: "Antarctica/Mawson", value: "MAWT", country: "Antarctica (Australia)" },
  { label: "Antarctica/McMurdo", value: "NZST", country: "Antarctica (New Zealand)" },
  { label: "Antarctica/Palmer", value: "CLT", country: "Antarctica (Chile)" },
  { label: "Antarctica/Syowa", value: "SYOT", country: "Antarctica (Japan)" },
  { label: "Antarctica/Troll", value: "GMT", country: "Antarctica (Norway)" },
  { label: "Arctic/Longyearbyen", value: "CET", country: "Norway" },
  { label: "Asia/Aden", value: "AST", country: "Yemen" },
  { label: "Asia/Almaty", value: "GMT+5", country: "Kazakhstan" },
  { label: "Asia/Amman", value: "GMT+3", country: "Jordan" },
  { label: "Asia/Ashgabat", value: "TMT", country: "Turkmenistan" },
  { label: "Asia/Baghdad", value: "AST", country: "Iraq" },
  { label: "Asia/Bahrain", value: "AST", country: "Bahrain" },
  { label: "Asia/Baku", value: "AZT", country: "Azerbaijan" },
  { label: "Asia/Bangkok", value: "ICT", country: "Thailand" },
  { label: "Asia/Beirut", value: "EET", country: "Lebanon" },
  { label: "Asia/Bishkek", value: "KGT", country: "Kyrgyzstan" },
  { label: "Asia/Brunei", value: "GMT+8", country: "Brunei" },
  { label: "Asia/Chita", value: "YAKT", country: "Russia" },
  { label: "Asia/Colombo", value: "IST", country: "Sri Lanka" },
  { label: "Asia/Damascus", value: "GMT+3", country: "Syria" },
  { label: "Asia/Dhaka", value: "BST", country: "Bangladesh" },
  { label: "Asia/Dili", value: "GMT+9", country: "Timor-Leste" },
  { label: "Asia/Dubai", value: "GST", country: "United Arab Emirates" },
  { label: "Asia/Dushanbe", value: "TJT", country: "Tajikistan" },
  { label: "Asia/Hebron", value: "EET", country: "Palestine" },
  { label: "Asia/Ho_Chi_Minh", value: "ICT", country: "Vietnam" },
  { label: "Asia/Hong_Kong", value: "HKT", country: "Hong Kong" },
  { label: "Asia/Hovd", value: "HOVT", country: "Mongolia" },
  { label: "Asia/Irkutsk", value: "IRKT", country: "Russia" },
  { label: "Asia/Jakarta", value: "WIB", country: "Indonesia" },
  { label: "Asia/Jayapura", value: "WIT", country: "Indonesia" },
  { label: "Asia/Jerusalem", value: "IST", country: "Israel" },
  { label: "Asia/Kabul", value: "AFT", country: "Afghanistan" },
  { label: "Asia/Kamchatka", value: "PETT", country: "Russia" },
  { label: "Asia/Karachi", value: "PKT", country: "Pakistan" },
  { label: "Asia/Kathmandu", value: "NPT", country: "Nepal" },
  { label: "Asia/Calcutta", value: "IST", country: "India" },
  { label: "Asia/Kuala_Lumpur", value: "MYT", country: "Malaysia" },
  { label: "Asia/Kuwait", value: "AST", country: "Kuwait" },
  { label: "Asia/Macau", value: "CST", country: "Macau" },
  { label: "Asia/Makassar", value: "WITA", country: "Indonesia" },
  { label: "Asia/Manila", value: "PHT", country: "Philippines" },
  { label: "Asia/Muscat", value: "GST", country: "Oman" },
  { label: "Asia/Nicosia", value: "EET", country: "Cyprus" },
  { label: "Asia/Novosibirsk", value: "NOVT", country: "Russia" },
  { label: "Asia/Omsk", value: "OMST", country: "Russia" },
  { label: "Asia/Phnom_Penh", value: "ICT", country: "Cambodia" },
  { label: "Asia/Pyongyang", value: "KST", country: "North Korea" },
  { label: "Asia/Qatar", value: "AST", country: "Qatar" },
  { label: "Asia/Riyadh", value: "AST", country: "Saudi Arabia" },
  { label: "Asia/Sakhalin", value: "SAKT", country: "Russia" },
  { label: "Asia/Seoul", value: "KST", country: "South Korea" },
  { label: "Asia/Shanghai", value: "CST", country: "China" },
  { label: "Asia/Singapore", value: "SGT", country: "Singapore" },
  { label: "Asia/Taipei", value: "GMT+8", country: "Taiwan" },
  { label: "Asia/Tashkent", value: "UZT", country: "Uzbekistan" },
  { label: "Asia/Tbilisi", value: "GET", country: "Georgia" },
  { label: "Asia/Tehran", value: "IRST", country: "Iran" },
  { label: "Asia/Thimphu", value: "BTT", country: "Bhutan" },
  { label: "Asia/Tokyo", value: "JST", country: "Japan" },
  { label: "Asia/Ulaanbaatar", value: "ULAT", country: "Mongolia" },
  { label: "Asia/Urumqi", value: "CST", country: "China" },
  { label: "Asia/Vientiane", value: "ICT", country: "Laos" },
  { label: "Asia/Vladivostok", value: "VLAT", country: "Russia" },
  { label: "Asia/Yangon", value: "MMT", country: "Myanmar" },
  { label: "Asia/Yekaterinburg", value: "YEKT", country: "Russia" },
  { label: "Asia/Yerevan", value: "AMT", country: "Armenia" },
  { label: "Atlantic/Azores", value: "AZOT", country: "Portugal" },
  { label: "Atlantic/Bermuda", value: "AST", country: "Bermuda" },
  { label: "Atlantic/Canary", value: "WET", country: "Spain" },
  { label: "Atlantic/Cape_Verde", value: "CVT", country: "Cape Verde" },
  { label: "Atlantic/Faroe", value: "WET", country: "Faroe Islands" },
  { label: "Atlantic/Reykjavik", value: "GMT", country: "Iceland" },
  { label: "Atlantic/South_Georgia", value: "GST", country: "South Georgia and the South Sandwich Islands" },
  { label: "Atlantic/St_Helena", value: "GMT", country: "Saint Helena" },
  { label: "Atlantic/Stanley", value: "FKST", country: "Falkland Islands" },
  { label: "Australia/Adelaide", value: "ACST", country: "Australia" },
  { label: "Australia/Brisbane", value: "AEST", country: "Australia" },
  { label: "Australia/Darwin", value: "ACST", country: "Australia" },
  { label: "Australia/Eucla", value: "ACWST", country: "Australia" },
  { label: "Australia/Lord_Howe", value: "LHST", country: "Australia" },
  { label: "Australia/Perth", value: "AWST", country: "Australia" },
  { label: "Australia/Sydney", value: "AEST", country: "Australia" },
  { label: "Etc/UTC", value: "UTC", country: "Universal Coordinated Time" },
  { label: "Europe/Amsterdam", value: "CET", country: "Netherlands" },
  { label: "Europe/Andorra", value: "CET", country: "Andorra" },
  { label: "Europe/Athens", value: "EET", country: "Greece" },
  { label: "Europe/Belgrade", value: "CET", country: "Serbia" },
  { label: "Europe/Berlin", value: "CET", country: "Germany" },
  { label: "Europe/Bratislava", value: "CET", country: "Slovakia" },
  { label: "Europe/Brussels", value: "CET", country: "Belgium" },
  { label: "Europe/Bucharest", value: "EET", country: "Romania" },
  { label: "Europe/Budapest", value: "CET", country: "Hungary" },
  { label: "Europe/Chisinau", value: "EET", country: "Moldova" },
  { label: "Europe/Copenhagen", value: "CET", country: "Denmark" },
  { label: "Europe/Dublin", value: "GMT", country: "Ireland" },
  { label: "Europe/Gibraltar", value: "CET", country: "Gibraltar" },
  { label: "Europe/Guernsey", value: "GMT", country: "Guernsey" },
  { label: "Europe/Helsinki", value: "EET", country: "Finland" },
  { label: "Europe/Isle_of_Man", value: "GMT", country: "Isle of Man" },
  { label: "Europe/Istanbul", value: "TRT", country: "Turkey" },
  { label: "Europe/Jersey", value: "GMT", country: "Jersey" },
  { label: "Europe/Kaliningrad", value: "EET", country: "Russia" },
  { label: "Europe/Kyiv", value: "EET", country: "Ukraine" },
  { label: "Europe/Lisbon", value: "WET", country: "Portugal" },
  { label: "Europe/Ljubljana", value: "CET", country: "Slovenia" },
  { label: "Europe/London", value: "GMT", country: "United Kingdom" },
  { label: "Europe/Luxembourg", value: "CET", country: "Luxembourg" },
  { label: "Europe/Madrid", value: "CET", country: "Spain" },
  { label: "Europe/Malta", value: "CET", country: "Malta" },
  { label: "Europe/Mariehamn", value: "EET", country: "Åland Islands" },
  { label: "Europe/Minsk", value: "MSK", country: "Belarus" },
  { label: "Europe/Monaco", value: "CET", country: "Monaco" },
  { label: "Europe/Moscow", value: "MSK", country: "Russia" },
  { label: "Europe/Oslo", value: "CET", country: "Norway" },
  { label: "Europe/Paris", value: "CET", country: "France" },
  { label: "Europe/Podgorica", value: "CET", country: "Montenegro" },
  { label: "Europe/Prague", value: "CET", country: "Czech Republic" },
  { label: "Europe/Riga", value: "EET", country: "Latvia" },
  { label: "Europe/Rome", value: "CET", country: "Italy" },
  { label: "Europe/Samara", value: "SAMT", country: "Russia" },
  { label: "Europe/San_Marino", value: "CET", country: "San Marino" },
  { label: "Europe/Sarajevo", value: "CET", country: "Bosnia and Herzegovina" },
  { label: "Europe/Simferopol", value: "MSK", country: "Russia (Crimea)" },
  { label: "Europe/Skopje", value: "CET", country: "North Macedonia" },
  { label: "Europe/Sofia", value: "EET", country: "Bulgaria" },
  { label: "Europe/Stockholm", value: "CET", country: "Sweden" },
  { label: "Europe/Tallinn", value: "EET", country: "Estonia" },
  { label: "Europe/Tirane", value: "CET", country: "Albania" },
  { label: "Europe/Vaduz", value: "CET", country: "Liechtenstein" },
  { label: "Europe/Vatican", value: "CET", country: "Vatican City" },
  { label: "Europe/Vienna", value: "CET", country: "Austria" },
  { label: "Europe/Vilnius", value: "EET", country: "Lithuania" },
  { label: "Europe/Warsaw", value: "CET", country: "Poland" },
  { label: "Europe/Zagreb", value: "CET", country: "Croatia" },
  { label: "Europe/Zurich", value: "CET", country: "Switzerland" },
  { label: "Indian/Antananarivo", value: "EAT", country: "Madagascar" },
  { label: "Indian/Chagos", value: "IOT", country: "British Indian Ocean Territory" },
  { label: "Indian/Christmas", value: "CXT", country: "Christmas Island" },
  { label: "Indian/Cocos", value: "CCT", country: "Cocos (Keeling) Islands" },
  { label: "Indian/Comoros", value: "EAT", country: "Comoros" },
  { label: "Indian/Kerguelen", value: "FSAT", country: "French Southern Territories" },
  { label: "Indian/Mahe", value: "SCT", country: "Seychelles" },
  { label: "Indian/Maldives", value: "MVT", country: "Maldives" },
  { label: "Indian/Mauritius", value: "MUT", country: "Mauritius" },
  { label: "Indian/Mayotte", value: "EAT", country: "Mayotte" },
  { label: "Indian/Reunion", value: "RET", country: "Réunion" },
  { label: "Pacific/Apia", value: "SST", country: "Samoa" },
  { label: "Pacific/Auckland", value: "NZST", country: "New Zealand" },
  { label: "Pacific/Bougainville", value: "BST", country: "Papua New Guinea" },
  { label: "Pacific/Chatham", value: "CHAST", country: "New Zealand" },
  { label: "Pacific/Chuuk", value: "CHUT", country: "Micronesia" },
  { label: "Pacific/Easter", value: "EAST", country: "Chile" },
  { label: "Pacific/Efate", value: "VUT", country: "Vanuatu" },
  { label: "Pacific/Fakaofo", value: "SST", country: "Tokelau" },
  { label: "Pacific/Fiji", value: "FJT", country: "Fiji" },
  { label: "Pacific/Funafuti", value: "TVT", country: "Tuvalu" },
  { label: "Pacific/Galapagos", value: "GALT", country: "Ecuador" },
  { label: "Pacific/Gambier", value: "GST", country: "French Polynesia" },
  { label: "Pacific/Guadalcanal", value: "SBT", country: "Solomon Islands" },
  { label: "Pacific/Guam", value: "ChST", country: "Guam" },
  { label: "Pacific/Honolulu", value: "HAST", country: "United States (Hawaii)" },
  { label: "Pacific/Kanton", value: "PHOT", country: "Kiribati" },
  { label: "Pacific/Kiritimati", value: "LINT", country: "Kiribati" },
  { label: "Pacific/Kosrae", value: "KOST", country: "Micronesia" },
  { label: "Pacific/Majuro", value: "MHT", country: "Marshall Islands" },
  { label: "Pacific/Marquesas", value: "MART", country: "French Polynesia" },
  { label: "Pacific/Midway", value: "GMT-11", country: "United States Minor Outlying Islands" },
  { label: "Pacific/Nauru", value: "NRT", country: "Nauru" },
  { label: "Pacific/Niue", value: "NUT", country: "Niue" },
  { label: "Pacific/Norfolk", value: "NFT", country: "Norfolk Island" },
  { label: "Pacific/Noumea", value: "NCT", country: "New Caledonia" },
  { label: "Pacific/Pago_Pago", value: "GMT-11", country: "American Samoa" },
  { label: "Pacific/Palau", value: "PWT", country: "Palau" },
  { label: "Pacific/Pitcairn", value: "PST", country: "Pitcairn Islands" },
  { label: "Pacific/Port_Moresby", value: "PGT", country: "Papua New Guinea" },
  { label: "Pacific/Rarotonga", value: "CKT", country: "Cook Islands" },
  { label: "Pacific/Saipan", value: "ChST", country: "Northern Mariana Islands" },
  { label: "Pacific/Tahiti", value: "TAHT", country: "French Polynesia" },
  { label: "Pacific/Tarawa", value: "GILT", country: "Kiribati" },
  { label: "Pacific/Tongatapu", value: "TOT", country: "Tonga" },
  { label: "Pacific/Wake", value: "WAKT", country: "Wake Island" },
  { label: "Pacific/Wallis", value: "WFT", country: "Wallis and Futuna" }
];


export const fieldsToFilter = ['lookup', 'createdTime', 'lastModifiedTime', 'createdBy', 'lastModifiedBy'];
export const fieldsToExcludeInFilter = ['links', 'lookup', 'datetime', 'attachment', 'json', 'id', 'createdTime', 'lastModifiedTime', 'createdBy', 'lastModifiedBy'];