export type FieldRendererType =
  | 'number' | 'boolean' | 'multiSelect' | 'select' | 'longText' | 'attachment' | 'text' | 'decimal' | 'year' | 'time' | 'datetime' | 'currency' | 'percent' | 'duration' | 'date' | 'email' | 'phoneNumber' | 'url' | 'rating' | 'user' | 'button' | 'json' | 'links' | 'createdTime' | 'lastModifiedTime' | 'createdBy' | 'lastModifiedBy' | 'formula' | 'lookup';

const fieldTypeMap: Record<string, FieldRendererType> = {
  text: 'text',
  number: 'number',
  decimal: 'decimal',
  year: 'year',
  time: 'time',
  datetime: 'datetime',
  date: 'date',
  email: 'email',
  phonenumber: 'phoneNumber',
  url: 'url',
  singleselect: 'select',
  multiselect: 'multiSelect',
  boolean: 'boolean',
  checkbox: 'boolean',
  rating: 'rating',
  currency: 'currency',
  percent: 'percent',
  duration: 'duration',
  json: 'json',
  attachment: 'attachment',
  file: 'attachment',
  user: 'user',
  button: 'button',
  createdtime: 'createdTime',
  lastmodifiedtime: 'lastModifiedTime',
  createdby: 'createdBy',
  lastmodifiedby: 'lastModifiedBy',
  uuid: 'text',
  links: 'links',
  lookup: 'lookup',
  formula: 'formula',
  longtext: 'longText',
  long_text: 'longText',
  textarea: 'longText',
  dropdown: 'multiSelect',
  radio: 'select',
  SingleLineText: 'text',
  LongText: 'longText',
  Number: 'number',
  Decimal: 'decimal',
  DateTime: 'datetime',
  Date: 'date',
  Email: 'email',
  PhoneNumber: 'phoneNumber',
  URL: 'url',
  SingleSelect: 'select',
  MultiSelect: 'multiSelect',
  Checkbox: 'boolean',
  Rating: 'rating',
  Currency: 'currency',
  Percent: 'percent',
  Duration: 'duration',
  Year: 'year',
  Time: 'time',
  JSON: 'json',
  Attachment: 'attachment',
  Button: 'button',
  User: 'user',
  CreatedTime: 'createdTime',
  LastModifiedTime: 'lastModifiedTime',
  CreatedBy: 'createdBy',
  LastModifiedBy: 'lastModifiedBy',
  Formula: 'formula',
};

export const normalizeFieldType = (type: string): FieldRendererType => {
  const normalizedType = (type || '').toLowerCase();
  return fieldTypeMap[normalizedType] || 'text'; // Default to 'text' if not found
};
